openapi: 3.0.0
info:
  title: Usersnap feedback project API
  description: Make feedback matter! Now with a RESTful API
  termsOfService: https://usersnap.com/terms-of-service
  contact:
    name: Usersnap Contact
    url: https://usersnap.com/contact
    email: contact@usersnap.com
  version: '0.1'
servers:
- url: https://platform.usersnap.com/v0.1
tags:
- name: project
  description: Project related endpoints
paths:
  /projects:
    get:
      tags:
      - project
      summary: Get all projects
      description: List all projects that are available for the current user
      operationId: getProjects
      responses:
        '200':
          description: Returns the list of projects
          content:
            application/json:
              schema:
                properties:
                  status:
                    type: boolean
                  data:
                    properties:
                      has_more:
                        type: boolean
                      count:
                        type: integer
                        format: int32
                      projects:
                        items:
                          properties:
                            project_id:
                              type: string
                            api_key:
                              type: string
                            company_id:
                              type: string
                            space_id:
                              type: string
                            created_at:
                              type: string
                              format: date-time
                            updated_at:
                              type: string
                              format: date-time
                            archived_at:
                              type: string
                              format: date-time
                            owner_id:
                              type: string
                            default_assignee_id:
                              type: string
                            name:
                              type: string
                            is_live:
                              type: boolean
                            feedback_count:
                              type: integer
                              format: int32
                            open_feedback_count:
                              type: integer
                              format: int32
                          type: object
                        type: array
                    type: object
                type: object
                example:
                  status: true
                  data:
                    has_more: false
                    count: 62
                    projects:
                    - project_id: 1d41f014-6331-4523-a45a-3782348d0a17
                      api_key: 79baa410-b3dd-4e03-86e5-8849d841473e
                      company_id: 695f0023-36ff-42dd-85a7-13afcd6a239d
                      space_id: 1da0d970-ec2a-4644-8eff-07a35b8c13e9
                      created_at: '2022-03-16T15:24:52.453839Z'
                      updated_at: '2022-11-28T11:29:22.261195Z'
                      archived_at: null
                      owner_id: 66e13ff6-509b-4385-9ef7-660167e972ba
                      default_assignee_id: null
                      name: Bug Tracking (Jira)
                      is_live: true
                      feedback_count: 1
                      open_feedback_count: 0
        '400':
          $ref: '#/components/responses/Error'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
      deprecated: false
      security:
      - bearerAuth: []
components:
  responses:
    Error:
      description: Error response
      content:
        application/json:
          schema:
            properties:
              status:
                type: boolean
              msg:
                type: string
              errortype:
                type: string
              errordata:
                type: object
            type: object
            example:
              status: false
              msg: Site does not exist
              errortype: SITE_NOT_FOUND
              errordata:
                site_id: 50c4cdd6-4801-42b9-b785-b5cf90fcbb65
    UnauthorizedError:
      description: Authorization header missing or invalid
      content:
        application/json:
          schema:
            properties:
              status:
                type: boolean
              msg:
                type: string
              errortype:
                type: string
              errordata:
                type: object
            type: object
            example:
              status: false
              msg: Authorization failed
              errortype: WRONG_AUTH
              errordata: {}
  securitySchemes:
    bearerAuth:
      type: http
      description: 'The bearer token is a JWT created by you and signed with the JWT secret provided in https://app.usersnap.com/#/settings/rest-api.


        To create it, start with a default HS256 JWT (e.g. https://jwt.io/#debugger-io) and add "kid": "<JWT ID>" to the headers. Then sign it using the JWT secret.


        Copy the resulting JWT (ey123123.ey123123.xyz) and always send it in the Authorization header as Bearer ey123123.ey123123.xyz.'
      scheme: bearer
      bearerFormat: JWT
externalDocs:
  description: Read our help pages for more.
  url: https://help.usersnap.com/reference/platform-rest-api
